spring.application.name=number-guessing-game

# PostgreSQL RDS
spring.datasource.url=jdbc:postgresql://numbergame-db.cbee2422soa3.eu-north-1.rds.amazonaws.com:5432/numbergame
spring.datasource.username=postgres
spring.datasource.password=Malavika3676

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# S3
aws.s3.bucket=malavika-files-2026-865679935327-ap-south-1-an
aws.region=ap-south-1

